export const dataOfBestSellerProduct = [
  {
    price: "$2.64 $2.74",
    description: "Fresh Green Leaf Lettuce",
    quuantity: "1 each",
    image: require("../../assets/images/BestSeller/i1.png").default,
  },
  {
    price: "$2.64 $2.74",
    description: "Fresh Green Leaf Lettuce",
    quuantity: "1 each",
    image: require("../../assets/images/BestSeller/i2.png").default,
  },
  {
    price: "$2.64 $2.74",
    description: "Fresh Green Leaf Lettuce",
    quuantity: "1 each",
    image: require("../../assets/images/BestSeller/i3.png").default,
  },
  {
    price: "$2.64 $2.74",
    description: "Fresh Green Leaf Lettuce",
    quuantity: "1 each",
    image: require("../../assets/images/BestSeller/i4.png").default,
  },
  {
    price: "$2.64 $2.74",
    description: "Fresh Green Leaf Lettuce",
    quuantity: "1 each",
    image: require("../../assets/images/BestSeller/i5.png").default,
  },
  {
    price: "$2.64 $2.74",
    description: "Fresh Green Leaf Lettuce",
    quuantity: "1 each",
    image: require("../../assets/images/BestSeller/i6.png").default,
  },
  {
    price: "$2.64 $2.74",
    description: "Fresh Green Leaf Lettuce",
    quuantity: "1 each",
    image: require("../../assets/images/BestSeller/i7.png").default,
  },
  {
    price: "$2.64 $2.74",
    description: "Fresh Green Leaf Lettuce",
    quuantity: "1 each",
    image: require("../../assets/images/BestSeller/i8.png").default,
  },
  {
    price: "$2.64 $2.74",
    description: "Fresh Green Leaf Lettuce",
    quuantity: "1 each",
    image: require("../../assets/images/BestSeller/i9.png").default,
  },
  {
    price: "$2.64 $2.74",
    description: "Fresh Green Leaf Lettuce",
    quuantity: "1 each",
    image: require("../../assets/images/BestSeller/i10.png").default,
  },
  {
    price: "$2.64 $2.74",
    description: "Fresh Green Leaf Lettuce",
    quuantity: "1 each",
    image: require("../../assets/images/BestSeller/i11.png").default,
  },
  {
    price: "$2.64 $2.74",
    description: "Fresh Green Leaf Lettuce",
    quuantity: "1 each",
    image: require("../../assets/images/BestSeller/i12.png").default,
  },
  {
    price: "$2.64 $2.74",
    description: "Fresh Green Leaf Lettuce",
    quuantity: "1 each",
    image: require("../../assets/images/BestSeller/i13.png").default,
  },
  {
    price: "$2.64 $2.74",
    description: "Fresh Green Leaf Lettuce",
    quuantity: "1 each",
    image: require("../../assets/images/BestSeller/i14.png").default,
  },
  {
    price: "$2.64 $2.74",
    description: "Fresh Green Leaf Lettuce",
    quuantity: "1 each",
    image: require("../../assets/images/BestSeller/i15.png").default,
  },
  {
    price: "$2.64 $2.74",
    description: "Fresh Green Leaf Lettuce",
    quuantity: "1 each",
    image: require("../../assets/images/BestSeller/i16.png").default,
  },
  {
    price: "$2.64 $2.74",
    description: "Fresh Green Leaf Lettuce",
    quuantity: "1 each",
    image: require("../../assets/images/BestSeller/i17.png").default,
  },
  {
    price: "$2.64 $2.74",
    description: "Fresh Green Leaf Lettuce",
    quuantity: "1 each",
    image: require("../../assets/images/BestSeller/i18.png").default,
  },
  {
    price: "$2.64 $2.74",
    description: "Fresh Green Leaf Lettuce",
    quuantity: "1 each",
    image: require("../../assets/images/BestSeller/i19.png").default,
  },
  {
    price: "$2.64 $2.74",
    description: "Fresh Green Leaf Lettuce",
    quuantity: "1 each",
    image: require("../../assets/images/BestSeller/i20.png").default,
  },
  {
    price: "$2.64 $2.74",
    description: "Fresh Green Leaf Lettuce",
    quuantity: "1 each",
    image: require("../../assets/images/BestSeller/i1.png").default,
  },
];
